(library
 (name ppx_quint_switch)
 (public_name ocaml-quint-connect.ppx-switch)
 (kind ppx_rewriter)
 (libraries ppxlib)
 (modules ppx_quint_switch)
 (preprocess (pps ppxlib.metaquot)))

(library
 (name ppx_quint_connect)
 (public_name ocaml-quint-connect.ppx)
 (kind ppx_rewriter)
 (libraries ppxlib)
 (modules ppx_quint_connect)
 (preprocess (pps ppxlib.metaquot)))
